### ISSUE TITLE
dcf77 - analyzer - clock

### ISSUE THREAD

**Issue by adebruijn** [deruiter/DCF77-Analyzer-Clock#1]
hello mr de ruiter, i am dutch too. 

want to make your dcf77 a-clock. very impressive design.

before i start to buy everything by Conrad, is there a kit available ? If there is, it is  easier for me because i am a beginner. I have downloaded al the files. where can i find the code to program the ardueno ?

Greetings

André de Bruijn
Voorhout
The netherlands

**Comment by deruiter** [comment]
Hello André, thanks for your interest in my clock. 

No, I have no kit for the clock... 

On the [Arduino website](http://forum.arduino.cc) you can find all the information you need to program the Arduino.
Reading your question, I think you are better off when you first familiarize yourself with the Arduino platform and the C++ programming language. 
This DCF Clock project is not for beginners, I think, although I was myself a beginner when I made it.
BUT I spent hundreds of hours (a year) on the Arduino forum and searching the internet to solve ANY problem I encountered. 
Be prepared to do a lot of study yourself, that is the only way to learn and it's very much worth it.

So buy an Arduino kit, and learn to program yourself first so you are able to understand the basics and then invest the money to make bigger projects. You will have a lot of fun learning and discovering the endless possibilities of the Arduino!

**Comment by adebruijn** [comment]
hoi erik,

Nog een vraagje, heb jij de benodigde printplaatjes te koop ? ik zag een heel stapeltje op een van je foto's.

scheelt me een heleboel werk. ik kan zelf etsen en heb een uv lamp etc, maar als je ze op de plank hebt ?

groet

André de Bruijn

afmdebruijn@me.com

06-22569679

---

Van: Erik notifications@github.com
Verzonden: maandag 25 juli 2016 09:03
Aan: deruiter/DCF77-Analyzer-Clock
CC: adebruijn; State change
Onderwerp: Re: [deruiter/DCF77-Analyzer-Clock] dcf77 - analyzer - clock (#1)

Closed #1https://github.com/deruiter/DCF77-Analyzer-Clock/issues/1.

##

**Comment by deruiter** [comment]
Hello André,

I like to keep the conversation in English so everyone can understand what's going on.

No, sorry I have no spare PCB's left.
I think etching yourself is not an option in this case because my designs are double sided and the margins are very tiny.

I alway order my pcb's at iTead, and you have them delivered in 2-3 weeks.

Good luck with your build!

**Comment by adebruijn** [comment]
hello,

what type of dcf antenna do you use ?

I use de one from conrad, but it does not give me a good signal.

if i run the superfilter program and looking at the serial monitor it seems to be to noisy. 

greetings andre

**Comment by brettoliver** [comment]
Hi I use this http://www.hkw-shop.de/Empfangstechnik-AM/Antenne-77-5kHz-10x100mm.html?listtype=search&searchparam=dcf77   There is a write up here on Udo's site https://blog.blinkenlight.net/experiments/dcf77/dcf77-receiver-modules/

**Comment by adebruijn** [comment]
The 10cm ferriet is producing now a perfect signal.

mr de ruiter, i use the common cathode display's, 
the type stated on your display prints. SC39 11 type

what do you mean with the line in your readme file:
Removed all the code to use Maxim 72xx chips with Common Anode displays

do i have to use te Common Anode ?

greetings

André

**Comment by deruiter** [comment]
Hello André, Glad you have a good signal now! 

In the Clock version 2.0 code, I do not use the [Sparkfun 4 digit display](https://www.sparkfun.com/products/9483) anymore. I used it before because it has a dot at the top left of the last digit so you can use it to display temperature as °C.

The short answer to your Q: you don't need to... ;)

The long answer:
To use Common ANODE displays with the Maxim 72xx chips is not possible because it will only drive common Cathode displays. But someone edited the 'standard' Ledcontrol.h library so with the adapted Ledcontrol.h library (on my github page) you CAN use CA displays by changing the extra BOOLEAN parameter to 'TRUE' when declaring a ledcontrol instance in the code.
(the last parameter as in the example of the 1.72 DCF Clock version of the code:

LedControl MaximCA = LedControl(MAXIMCADATA, MAXIMCACLK, MAXIMCALD, 1, **true**);

Anyway, I now use for the temperature display a common Cathode display and on that display I rotated the right (last) 7 segment display 180 degrees and rewired the dot and 'G' segments.
So when I want to lit the 'degree dot', I simply activate the 'dot' of that digit.

In the coming weks I will update my DCF77 Analyzer / Clock 2.0 page on the [Arduino Project hub](https://create.arduino.cc/projecthub/edr1924/dcf77-analyzer-clock-v2-0-c25404?ref=user&ref_id=96287&offset=0) so you can see how I build the 2.0 clock. I also have a few front panels left if you are interested. (Updating the page is slow because I have eye problems.)

Good luck with your build!

**Comment by adebruijn** [comment]
Thanks for your quick and very usefull answer(s)

I made an experimentel setup to check if my self made print's are working. mostly your design, but no bridges. A lot of work wiring the outer cirkel !!!! but all works fine.

only the R SET resistor is difficult to define: with 220ohm the leds are bright on the outer ring,
but when the program starts, and the ring selftest displays the led's back and forth, it does only 30-50%. with 28K the leds are dim, but the selftest works ok all led's go on and off.

what Resistor do you use voor the outer en inner ring ?

i am intererested in one of your front panels !

greetings

andre

**Comment by deruiter** [comment]
Hi André, For the right resistor value for the LED's, you need to look at the [maxim 72xx datasheet pages 10 and 11](https://datasheets.maximintegrated.com/en/ds/MAX7219-MAX7221.pdf)

I don't know what value I used but I think it was 27K because the most common LED's as a guideline have a Forward Voltage of 2 to 2,5V and a current of 20mA. 
In any case, 220 Ohm is way to low! The maxim chip cannot handle the large currents flowing so that's the reason I think some LED's are not lit at all

If the led's are not bright enough **at maximum brightness setting in the code**, then your only option is to use other LED's.  The LED's I used are very bright at the V/I values mentioned. Other LED's I have are very dim in comparison but are cheap.

I don't know yet how to pass my private email address to you so we can arrange the front panel sale but when I do I will let you know.

**Comment by GvLaere** [comment]
Hello sir,
Your project is really wonderful! I can understand that this had taken a lot of time! 
I'm a beginner and have less experience Arduino. I just make simple projects. 
My question is if you have a suggestion where I can find just a clock with DCF77 with only 6 digits 7 segment LED (hours, minutes and seconds). I have huge LED 7 segments display's and I want to make a clock with DCF77. For me it is not simple to extract the right code and sketch out of your project.
Thanks for your help!
Greeting Guido
Oirschot / The Netherlands

**Comment by deruiter** [comment]
Hello Guido, thanks for your comments. I suggest using Google to search for another project with DCF77. for example "DCF77 clock arduino" will give you the result you are looking for.

**Comment by adebruijn** [comment]
Hello mr de Ruiter,

Your clock design is ready. I made all the prints, had to redesign them though, and all is working. only some trouble with the PIR. I had bought the Conrad PIR A27/360. This was not working directly with your design. So for everybody who also want to make this nice clock from mr de ruiter, here my design for an interface to connect the PIR to the PIR port D3 on mr de Ruiters DCF Analalyzer.

PIRprint.PDF is the schematic
In the ZIP the Eagle files

Greetings André

[pirprint.pdf](https://github.com/deruiter/DCF77-Analyzer-Clock-V2.0/files/504849/pirprint.pdf)

![pirprint](https://cloud.githubusercontent.com/assets/20625661/19019789/943f4bdc-8893-11e6-819f-8dabc0e5966a.jpg)

[pirprint.zip](https://github.com/deruiter/DCF77-Analyzer-Clock-V2.0/files/504850/pirprint.zip)

**Comment by adebruijn** [comment]
strange behavior .....

Do you recognize this problem mr de de ruiter ?

the 6th display print with the time display, does not work with the max7221 but only a max 7219.
when I change the 7221 with another chip out of a working first or second etc board no change. if I change the board to fourth or any other position in the chain it works with the 7221. I do not understand. Any ideas ?

so  in pos 6 (last in chain, nr 7) only with a 7219 the display work.

if I switch on, all display's also nr 6 with 7221 lights up. then the display test follows, nr 6 doesn't work. replacing with a 7219 no problems.

al is working and now I start to make the case. i have a 3d printer, and making a front with all the holes is very easy !!! over the white ABS printed frontplate i use a transparent printer sheet to make the decals. after this a thin 2mm glass plate finishes the front plate. 

This is the plan, if it works i put in a few pics.

**Comment by adebruijn** [comment]
hello mr de Ruiter,

I have noticed someting, the pulse width when in super filter mode and only in the meteo range,
is the pulse width 177-183 when low (0), and 199-201 when high. (1)

this gives as result if I do not edit the value 170 to 185 in 

```
// process DCF bits
//--------------------------------------------------------------------------------
// distinguish between long and short pulses
if (trailingEdge - leadingEdge < 185) //org 170
{
```

that all the bits from 2- 15 are registred high (1).

if I switch the filter off, the bits are low 99-101 en high 199-201 in the whole range from 1-58.

???????

**Comment by deruiter** [comment]
Hello André, 

Q1: I only use the Maxim 7221 chips because of the lower MRI.  I do not recognize the problem you have?  Do you use genuine versions of the Maxims?  I did use Chinese chips first but not anymore...

Q2: The superfilter has 3 modes, maybe you can use one of the other modes? I think it was in BASIC mode, the meteo bits are left alone and passed through "as-is" in the Superfilter sketch.
That said, I did not experience the problem myself. So I cannot replicate the problem and help you solve it.  For detailed support concerning the Superfilter, I think it's better to ask the maker Udo Klein.  

I'm sorry I cannot help you! Hopefully you are able to get around these issues...

Looking forward to see your 3D printed front panel design!

**Comment by adebruijn** [comment]
hello mr de Ruiter thanks for your answer. I replaced all the MAX7221. One was faulty I think and did not let nr 7 get trough. But the funny thing, it let the 7219 in nr 7 through anyway !.

You can check the faulty pulse width in bit 1-14, put superfilter OFF, and look at the pulse width numbers, the bits are low 99-101 en high 199-201 in the whole range from 1-58. (if you have a good reception of the singal offcourse) BUT, with superfilter in 1/2/3 mode it gives a pulse width 177-183 when low (becomes 1), and 199-201 when high. (1) only in bit 1-14 . Rest is normal. Before I sent an email to Udo I want to make sure I am not the only one.

I put a sketchup 3D sketch picture in, you can see all the islands where all the print plates can be put.

Greetings André
![dcf77v5](https://cloud.githubusercontent.com/assets/20625661/19420165/1919d572-93e6-11e6-9614-7060d5125fb6.jpg)

**Comment by adebruijn** [comment]
And one from another angle
![dcf77v5a](https://cloud.githubusercontent.com/assets/20625661/19457827/78f67c24-94c8-11e6-9a71-4c9a510b6806.jpg)

**Comment by adebruijn** [comment]
ready !!! only the decal sheet for the front en the glassplate. 
then All on top of a nice box.

![img_6213](https://cloud.githubusercontent.com/assets/20625661/19699964/a01d252c-9af5-11e6-826d-541020a623a1.JPG)
![img_6214](https://cloud.githubusercontent.com/assets/20625661/19699960/9f610ca2-9af5-11e6-9e9e-cd37ddd39c1b.JPG)

**Comment by deruiter** [comment]
Wow, this is quite a feat of engineering... Certainly it looks a lot neater than the wiring in my clock ;)
This has been a lot of work, making all those custom pcb's.

Thanks for the foto's, looking forward to the finished clock in it's casing!

**Comment by adebruijn** [comment]
coming right up !!!! thanks for your nice sketch'es and scematic !!!

**Comment by adebruijn** [comment]
just an update which had to be much earlier....

![IMG_5459_Moment](https://user-images.githubusercontent.com/20625661/133894723-5cc7e4f2-e542-4ce0-97e3-1823adb6cb21.jpg)
.

**Comment by adebruijn** [comment]
with new designed/pcb for bigger displays for the date and time

**Comment by deruiter** [comment]
> with new designed/pcb for bigger displays for the date and time

I thought the inside was beautiful but the final clock is even more amazing...!   What a lot of work but the result is worth it... :)   
Thank you very much for sharing this photo. 

Greetings!
Erik
